- name: PLAY-1
  hosts: localhost
  tasks: 
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "hello from PLAY-1 and TASK-1"

- name: PLAY-2
  hosts: localhost
  tasks: 
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "hello from PLAY-1 and TASK-1"      