- name: Variable for PLAY Level
  hosts: localhost
  tasks: 
    - name: check variable
      ansible.builtin.debug:
        msg: "Hi, I am {{ Course }} taught by {{ Trainer }} for a duration of {{ Duration }}."
